//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellarisSaveGameEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StellarisSaveGameEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when loading the selected planet data. Please choose another planet..
        /// </summary>
        internal static string Main_comboBoxChoosePlanet_SelectedIndexChanged_There_was_an_error_when_loading_the_selected_planet_data {
            get {
                return ResourceManager.GetString("Main_comboBoxChoosePlanet_SelectedIndexChanged_There_was_an_error_when_loading_th" +
                        "e_selected_planet_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a file....
        /// </summary>
        internal static string Main_Main_Please_open_a_file {
            get {
                return ResourceManager.GetString("Main_Main_Please_open_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not read file from disk. Original error: .
        /// </summary>
        internal static string Main_openToolStripMenuItem_Click_Error__Could_not_read_file_from_disk__Original_error__ {
            get {
                return ResourceManager.GetString("Main_openToolStripMenuItem_Click_Error__Could_not_read_file_from_disk__Original_e" +
                        "rror__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File opened successfully!.
        /// </summary>
        internal static string Main_openToolStripMenuItem_Click_File_opened_successfully {
            get {
                return ResourceManager.GetString("Main_openToolStripMenuItem_Click_File_opened_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file....
        /// </summary>
        internal static string Main_openToolStripMenuItem_Click_Opening_file {
            get {
                return ResourceManager.GetString("Main_openToolStripMenuItem_Click_Opening_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sav files (*.sav)|*.sav.
        /// </summary>
        internal static string Main_openToolStripMenuItem_Click_sav_files {
            get {
                return ResourceManager.GetString("Main_openToolStripMenuItem_Click_sav_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved..
        /// </summary>
        internal static string Main_saveToolStripMenuItem_Click_File_saved {
            get {
                return ResourceManager.GetString("Main_saveToolStripMenuItem_Click_File_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_saveToolStripMenuItem_Click_Save {
            get {
                return ResourceManager.GetString("Main_saveToolStripMenuItem_Click_Save", resourceCulture);
            }
        }
    }
}
